config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  post 'braintree/checkout'
  root 'welcome#index'

#*** rails g clearance:routes show all these default Clearance routes
resources :passwords, controller: "clearance/passwords", only: [:create, :new]
resource :session, controller: "clearance/sessions", only: [:create]
resources :users, controller: "clearance/users", only: [:create] do
  resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]

  end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"
#*** end of default routes of Clearance

resources :users, controller: "users", only: [:show, :edit, :update, :index]
resources :listings do
  resources :reservations, only: [:create, :show]
end

resources :reservations, only: [:show, :destroy]

#Route that redirects the user from Facebook(the provider) to the app
get "/auth/:provider/callback" => "sessions#create_from_omniauth"


end

app/models/listing.rb
class Listing < ApplicationRecord

# Validaitons
validates :title, presence: true

# Associations
belongs_to :user
has_many :reservations

# Pagination - gem 'kaminari'
paginates_per 5

# Image Uploading - gem 'Carrierwave'
serialize :photos, Array
mount_uploaders :photos, PhotoUploader

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only: [:show, :edit, :update, :destroy ]

  def index
    @listings = Listing.order(:title).page params[:page]
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      flash[:success] = "Your listing has been created"
      redirect_to root_path
    else
      flash[:error] = "Error in creating listing"
      render "listings/new"
    end
  end

  def show
    @reservation = @listing.reservations.new
  end

  def edit
    # @listing = Listing.find(params[:id])
  end

  def update
    # @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      flash[:success] = "Successfully updated the listing!"
      redirect_to root_path
    else
      flash[:error] = "Error in updating listing"
      render "listings/edit"
    end
  end

  def destroy
    # @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to root_path
  end

  private
  def listing_params
    params.require(:listing).permit(:title, :location, :description, :available_from, :available_to, :capacity, {photos: []})
  end


  def find_listing
    @listing = Listing.find(params[:id])
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<!-- form for new and edit listings  -->

<!-- title -->
<div class="text-field">
  <%= form.label :title %>
  <%= form.text_field :title  %>
</div>

<!-- location -->
<div class="text-field">
  <%= form.label :location %>
  <%= form.text_field :location %>
</div>

<!-- description -->
<div class="text-field">
  <%= form.label :listing_description %>
  <%= form.text_area :description %>
</div>

<!-- available from -->
<div class="date-field">
  <%= form.label :available_from %>
  <%= form.date_field :available_from, type: 'date' %>
</div>

<!-- available to -->
<div class="date-field">
  <%= form.label :available_to %>
  <%= form.date_field :available_to, type: 'date' %>
</div>

<!-- capacity -->
<div class="text-field">
  <%= form.label :number_of_guests %>
  <%= form.number_field :capacity, type: 'number'  %>
</div>

<!--photos-->
<div class="text-field">
  <%= form.label :photos %>
  <%= form.file_field :photos, multiple: true  %>
</div>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

<%= form_for @listing do |form| %>
  <%= render partial: 'form', object: form %>
  <%= form.submit %>
<% end %>

app/views/listings/index.html.erb
<h2>All Listings</h2>
<p>Find me in app/views/listings/index.html.erb</p>

<% @listings.each do |listing| %>
  <%= link_to listing.title, listing_path(listing) %>
  <%= button_to ("Update"), edit_listing_path(listing), method: :get %>
  <%= button_to ("Delete"), listing_path(listing), method: :delete %>
<% end %>


<%= paginate @listings %>

app/views/listings/new.html.erb
<h1>Listings#new</h1>
<p>Find me in app/views/listings/new.html.erb</p>

<%= form_for @listing do |form| %>
  <%= render partial: 'form', object: form %>
  <%= form.submit %>
<% end %>

app/views/listings/show.html.erb
<h1>Title: <%= @listing.title %></h1>
<div>
  Posted By: <%= @listing.user.email %> (<%= @listing.user.id %>)

</div>
___________________________________________________________________________
  <p>Location: <%= @listing.location %></p>
  <p>Description: <%= @listing.description %></p>
  <p>Max guests: <%= @listing.capacity %></p>
  <p>Available From: <%= @listing.available_from %></p>
  <p>Available To: <%= @listing.available_to %></p>
  <!-- <%= link_to "Edit", edit_listing_path(@listing) %> -->
  <%= render "reservations/form" %>

<!-- Carousel displaying pictures of listing -->
<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
      <% @listing.photos.each do |photo| %>
        <% if photo == @listing.photos.first %>
        <div class="item active" >
          <%= image_tag photo %>
        </div>
        <% else %>
        <div class="item">
          <%= image_tag photo %>
        </div>
        <% end %>
      <% end %>
  </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>