config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  post 'braintree/checkout'
  root 'welcome#index'

#*** rails g clearance:routes show all these default Clearance routes
resources :passwords, controller: "clearance/passwords", only: [:create, :new]
resource :session, controller: "clearance/sessions", only: [:create]
resources :users, controller: "clearance/users", only: [:create] do
  resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]

  end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"
#*** end of default routes of Clearance

resources :users, controller: "users", only: [:show, :edit, :update, :index]
resources :listings do
  resources :reservations, only: [:create, :show]
end

resources :reservations, only: [:show, :destroy]

#Route that redirects the user from Facebook(the provider) to the app
get "/auth/:provider/callback" => "sessions#create_from_omniauth"


end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :email, uniqueness: true
  has_many :authentications, :dependent => :destroy
  has_many :listings
  has_many :reservations

  # upload profile photo
  mount_uploader :image, ImageUploader


  #create a User object based on the information given by the provider
  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = User.create!(name: auth_hash["name"], email: auth_hash["extra"]["raw_info"]["email"])
      user.authentications << (authentication)
      return user
  end


  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
     true
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Profile Updated!"
      redirect_to root_path
    else
      flash[:error] = "Error in updating profile"
      render "users/edit"
    end
  end

  def destroy
   @user = current_user
   @user.destroy
   redirect_to root_path
  end


  private
  def user_params
      params.require(:user).permit(:email, :password, :image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<!-- only allow password field on sign in page  -->
<% unless signed_in? %>
<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
<% end %>

<!-- only allow edit profile picture when signed in (in edit user) -->
<% if signed_in? %>
<div>
  <%= form.label :Your_Profile_Picture%></br>
  <%= image_tag(@user.image_url) if @user.image? %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_for @user do |form| %>
  <%= render partial: 'form', object: form %>
  <%= form.submit %>
<% end %>

<%= button_to ("View Profile"), user_path(current_user), method: :get %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
Users#show


<h1>Email: <%= @user.email %> </h1>
<h1>Password: <%= @user.password %> </h1>