config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  post 'braintree/checkout'
  root 'welcome#index'

#*** rails g clearance:routes show all these default Clearance routes
resources :passwords, controller: "clearance/passwords", only: [:create, :new]
resource :session, controller: "clearance/sessions", only: [:create]
resources :users, controller: "clearance/users", only: [:create] do
  resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]

  end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"
#*** end of default routes of Clearance

resources :users, controller: "users", only: [:show, :edit, :update, :index]
resources :listings do
  resources :reservations, only: [:create, :show]
end

resources :reservations, only: [:show, :destroy]

#Route that redirects the user from Facebook(the provider) to the app
get "/auth/:provider/callback" => "sessions#create_from_omniauth"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Air BnB</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tag %>
</head>
<body>

  <div class="container-fluid">
    <div class = "header">
      <div class="title"><a href="">Welcome to Air BnB </a></div>
    <% if signed_in? %>
      <%= link_to ("New Listing"), new_listing_path %>
      <%= link_to ("All Listings"), listings_path %>
      <%= link_to ("Edit Profile"), edit_user_path(current_user) %>
      <%= link_to ("Reservations"), reservation_path(current_user) %>
      <%= button_to ("Sign Out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end %>
    </div>
  </div>

<div id="flash">
  <% flash.each do |key, value| %>
    <% if value.class == Array %>
      <% value.each do |message| %>
        <div class="<%= flash_class(key) %>">
          <p><%= message %></p>
        </div>
      <% end %>
    <% else %>
      <div class="<%= flash_class(key) %>">
        <p><%= value %></p>
      </div>
    <% end %>
  <% end %>
</div>

<%= yield %>
</body>

</html>